name: EXIT Test

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: windows-2022
    steps:
      - name: Get Last commit sha
        id: lastsha1
        run: |
          $commit = git ls-remote https://github.com/rime/librime/ master
          $commitParts = $commit -split '\s+'
          $commitsha = $commitParts[0]
          "commitsha=$commitsha" |  Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "needupdate=$false" |  Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "librime commit SHA: $commitsha"
          echo "sha=$commitsha" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
          
      - name: Create cache
        id: cache-commit-sha1
        uses: actions/cache@v3
        with:
          path: ${{ runner.workspace }}  # 缓存整个工作目录
          key: ${{env.commitsha}}  # 使用 commit SHA 作为缓存的 key
          
      - name: Create out.txt with commit SHA
        if: steps.cache-commit-sha1.outputs.cache-hit == 'true' 
        continue-on-error: true
        run: |
          #"needupdate=$true" |  Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          exit 1
  
  job2:
    runs-on: windows-2022
    if: always() && (needs.job1.result == 'success')
    needs: job1
    steps:
      - name: Get Last commit sha
        id: lastsha
        run: |
          $commit = git ls-remote https://github.com/rime/librime/ master
          $commitParts = $commit -split '\s+'
          $commitsha = $commitParts[0]
          "commitsha=$commitsha" |  Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "librime commit SHA: $commitsha"
          echo "sha=$commitsha" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
          #echo ${{jobs.lastsha1.result}}
      - name: Test env
        run: |
          echo "From outputs"
          echo $env:SHA
          echo "From env"
          echo $env:commitsha
        env:
          SHA: ${{steps.lastsha.outputs.sha}}
          

      - name: Cache commit SHA
        id: cache-commit-sha
        uses: actions/cache@v3
        with:
          path: ${{ runner.workspace }}  # 缓存整个工作目录
          key: cache-${{env.commitsha}}  # 使用 commit SHA 作为缓存的 key
          
      - name: Create out.txt with commit SHA
        if: steps.cache-commit-sha.outputs.cache-hit != 'true' 
        run: |
          $commit_sha_from_job1=$env:commitsha
          echo "Commit SHA from job1: $commit_sha_from_job1" > out.txt
      - name: OutPut commit SHA
        run: |
          write-host "test:"
          cat out.txt
          